// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwlszixrwaomxzyblznb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bHN6aXhyd2FvbXh6eWJsem5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTI4OTIsImV4cCI6MjA2Nzg2ODg5Mn0.ZeSzdsQV4Otrd3oPFOq5DqGUVExv_OgWGerezgBQkrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});